title: Code BEAM Mexico
description: "The major Elixir and Erlang event in México. The Elixir and Erlang community celebrates ten years of Elixir in Mexico City. Meet people and companies using and developing high performance, fault-tolerant and resilient applications that scale to billions of users in production in areas like Fintech, eCommerce, IoT, Gaming, Blockchain, Security, Machine Learning and more."
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://codebeammexico.com/" # the base hostname & protocol for your site

logo: "./assets/images/logo2022.png"

# google_site_verification: googleXXXXXXXXXXXXXXXX.html

include: [archives]
         [admin]

exclude:
- docs/
- archives/
- legacy-content/
- bin/

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/codebeamio
    username: codebeamio
    card: image

# Build settings
markdown: kramdown
permalink: pretty

collections:
  participants:
    output: true
  keynotes:
    output: true
  trainers:
    output: true
  trainings:
    output: true
  talks:
    output: true
  posts:
    output: true
  videos:
    output: true
#  archive:
#    output: true

defaults:
  - scope:
      path: ""
      type: "participants"
    values:
      layout: "participant"
  - scope:
      path: ""
      type: "trainings"
    values:
      layout: "training"
  - scope:
      path: ""
      type: "talks"
    values:
      layout: "talk"
  - scope:
      path: ""
      type: "keynotes"
    values:
      layout: "talk"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "videos"
    values:
      layout: "video"
#  - scope:
#      path: ""
#      type: "archives"
#    values:
#      layout: "archive"
  - scope:
      path: ""
    values:
      layout: "default"

# Google Map JS api
# This is my api for this template
key-api: AIzaSyBf-F7nBzxi_73uI9QUxRQ-cNihYtlZ_AA
map-text: Code Spaces, CDMX
map-text-location: Facultad de Ingeniería, UNAM
map-lat: 19.3314918
map-lng: -99.1849444
