#!/usr/bin/env bash

if [[ "$1" == "site" ]]; then

  echo "Update published site"

  bundle exec jekyll clean
  rm -rf docs/
  mkdir docs
  bundle exec jekyll build
  cp -r _site/* docs/

else

  echo "Start jekyll auto incremental"

  bundle exec jekyll clean  
  bundle exec jekyll serve --incremental --host=0.0.0.0

fi

