#!/usr/bin/env bash

if [[ "$1" == "site" ]]; then

  echo "Update published site"

  bundle exec jekyll clean
  rm -rf docs/
  mkdir docs
  bundle exec jekyll build --incremental
  cp -r _site/* docs/

elif [[ "$1" == "live" ]]; then

  echo "Start jekyll auto livereload"

  bundle exec jekyll clean  
  bundle exec jekyll serve --livereload --host=0.0.0.0


elif [[ "$1" == "help" ]]; then

  echo "publish            #local server"
  echo "publish live       #local server with livereload"
  echo "publish site       #regenerate full site on docs/"
  exit 0

else

  echo "Start jekyll auto incremental"

  bundle exec jekyll clean  
  bundle exec jekyll serve --incremental --host=0.0.0.0

fi

